name: CI Testing

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use latest node.js version
        uses: actions/setup-node@v2.1.5
        with:
          check-latest: true
      - name: Install dependencies
        run: npm ci
#       - name: Lint
#         run: npm run lint
      - name: Test
        run: npm run test
      - name: Deploy
        uses: serverless/github-action@v2.18.0
        with:
          args: deploy --stage test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
